### ISSUE TITLE
hooks not working on Anthropic/LiteLLM

### ISSUE THREAD

**Issue by josepablog** [instructor-ai/instructor#1083]
**What Model are you using?**

- [ ] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [ ] gpt-4
- [x ] Other Anthropic

**Describe the bug**
Hooks are not working on latest instructor (1.5.2)

**To Reproduce**
This is not working from `LiteLLM` or `Anthropic` :

When I attempt:
```
client = instructor.from_anthropic(AnthropicBedrock()) #instructor.from_litellm(completion)
client.on("completion:kwargs", self.log_completion_kwargs)
```

``` 
_feedback.py", line 78, in get_llm_response
client.on("completion:kwargs", self.log_completion_kwargs)
^^^^^^^^^
AttributeError: 'Instructor' object has no attribute 'on'
```

**Comment by ivanbelenky** [comment]
I think this changes will be released with 1.6.0. @jxnl correct me if I am wrong

Check https://github.com/instructor-ai/instructor/pull/1065

If you want to use them, I would suggest cloning and building from `main` branch or adding a git dependency to your `pyproject.toml`

**Comment by josepablog** [comment]
ahh ok, thank you.  I would recommend using a feature branch for changes that are not in the pip repository yet, as the readme in GitHub works as authoritative documentation :)

**Comment by ivanbelenky** [comment]
your welcome. I agree fully with your comment above.

**Comment by jxnl** [comment]
should be fixed now
